// default package
// Generated Apr 17, 2019 11:57:40 AM by Hibernate Tools 5.0.6.Final
package entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Phonenumber generated by hbm2java
 */
@Entity
@Table(name = "PHONENUMBER", schema = "SCOTT")
public class Phonenumber implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String phonenumber;

	public Phonenumber() {
	}
	
	public Phonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}
	public Phonenumber(long id, String phonenumber) {
		this.id = id;
		this.phonenumber = phonenumber;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "phone_seq")
	@SequenceGenerator(name = "phone_seq", sequenceName = "phone_seq", allocationSize = 1, initialValue = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}
	
	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

}
